name: Manual Cucumber Tests

on:
  workflow_dispatch:   # run manually

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: maven

      # Build and run tests
      - name: Build with Maven and run Cucumber tests
        run: mvn clean verify -B

      # Upload cucumber HTML report as artifact
      - name: Upload Cucumber HTML Report
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-html-report
          path: target/HTML-reports
